[tool.poetry]
name = "nephelaiio-docker"
version = "0.1.0"
description = ""
authors = ["Ted Cook <teodoro.cook@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
yamllint = "^1.32.0"
ansible = "^8.5.0"
ansible-lint = { version = "*", markers = "platform_system != 'Windows'" }
molecule-plugins = "^23.5.0"
requests = "^2.31.0"
docker = "^6.1.3"
molecule = "^6.0.2"
netaddr = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
